package ru.ystu.rating.university.dto;

public record BParamsDto(
        Integer year,
        // original B11..B21 inputs
        Double ENa,
        Double ENb,
        Double ENc,
        Double Eb,
        Double Ec,
        Double beta121,
        Double beta122,
        Double beta131,
        Double beta132,
        Double beta211,
        Double beta212,
        // additional inputs for extended metrics
        Double NBP,
        Double NMP,
        Double ACP,
        Double OPC,
        Double ACC,
        Double PKP,
        Double PPP,
        Double NP,
        Double NOA,
        Double NAP,
        Double B25_o,
        Double B26_o,
        Double UT,
        Double DO,
        Double N,
        Double Npr,
        Double VO,
        Double PO,
        Double B33_o,
        // inputs for additional metrics
        Double NR2023,
        Double NR2024,
        Double NR2025,
        Double WL2022,
        Double WL2023,
        Double WL2024,
        Double NPR2022,
        Double NPR2023,
        Double NPR2024,
        Double DN2022,
        Double DN2023,
        Double DN2024,
        Double Io,
        Double Iv,
        Double Iz,
        Double No,
        Double Nv,
        Double Nz,
        Double OD2022,
        Double OD2023,
        Double OD2024,
        Double PN2022,
        Double PN2023,
        Double PN2024
) {
}

